language: java
env:
  global:
    - RAVEN_Security_Certificate_Password=
      RAVENDB_JAVA_TEST_SERVER_PATH=./RavenDB/Server/Raven.Server
      RAVENDB_JAVA_TEST_CERTIFICATE_PATH=$TRAVIS_BUILD_DIR/certs/server.pfx
      RAVENDB_JAVA_TEST_HTTPS_SERVER_URL=https://a.javatest11.development.run:8085
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libunwind8 wget libicu52 libssl-dev curl unzip gettext libcurl4-openssl-dev zlib1g uuid-dev bzip2 openssl
  - mkdir ./certs; pushd certs
  - openssl genrsa -out ca.key 2048
  - openssl req -new -x509 -key ca.key -out ca.crt -subj "/C=US/ST=Arizona/L=Nevada/O=RavenDB Test CA/OU=RavenDB test CA/CN=a.javatest11.development.run/emailAddress=ravendbca@example.com"
  - openssl genrsa -out localhost.key 2048
  - openssl req -new  -key localhost.key -out localhost.csr -subj "/C=US/ST=Arizona/L=Nevada/O=RavenDB Test/OU=RavenDB test/CN=a.javatest11.development.run/emailAddress=ravendb@example.com"
  - openssl x509 -req -extensions ext -extfile ../src/test/cert/test_cert.conf -in localhost.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out localhost.crt
  - cat localhost.key localhost.crt > jvm.pem
  - openssl pkcs12 -passout pass:$RAVEN_Security_Certificate_Password -export -out server.pfx -inkey localhost.key -in localhost.crt
  - sudo cp ca.crt /usr/local/share/ca-certificates/ca.crt
  - sudo update-ca-certificates
  - popd  
  - wget -O RavenDB.tar.bz2 https://hibernatingrhinos.com/downloads/RavenDB%20for%20Linux%20x64/latest?buildType=nightly
  - tar xvjf RavenDB.tar.bz2
  - sleep 2
script: mvn test
